In [1]:
import numpy as np
import random

def placeQueens(queensPos, board, N):
  for i in range(N):
    min = np.min(board[i])
    minIndex = []

    for j in range(len(board[i])):
      if board[i][j] == min:
        minIndex.append(j)
    randSpot = random.randint(0, len(minIndex) - 1)
    queensPos[i] = minIndex[randSpot]
    board = updateGame(queensPos[i], i, board, N)
  return queensPos, board

def moveQueens(queensPos, board, Row, N):

  temp = board[Row].copy()
  temp[queensPos] = np.nan
  min = np.nanargmin(temp)
  minIndex = []


  for j in range(len(temp)):
    if temp[j] == temp[min]:
      minIndex.append(j)
  randSpot = random.randint(0, len(minIndex) - 1)
  board = neg_updateGame(queensPos, Row, board, N)
  queensPos = minIndex[randSpot]
  board = updateGame(queensPos, Row, board, N)
  temp = board[Row]
  return queensPos, board


def neg_updateGame(oldQueen, row, oldBoard, N):
  for i in range(N):
    if i == row:
      continue
    diff = i - row
    rDiagonal = oldQueen + diff
    lDiagonal = oldQueen - diff
    oldBoard[i,oldQueen] -= 1
    if rDiagonal >= 0 and rDiagonal < N:
      oldBoard[i,rDiagonal] -= 1

    if lDiagonal >= 0 and lDiagonal < N:
      oldBoard[i,lDiagonal] -= 1
  return oldBoard

def updateGame(newQueen, row, oldBoard, N):
  for i in range(N):
    if i == row:
      continue
    diff = i - row
    rDiagonal = newQueen + diff
    lDiagonal = newQueen - diff
    oldBoard[i,newQueen] += 1
    if rDiagonal >= 0 and rDiagonal < N:
      oldBoard[i,rDiagonal] += 1

    if lDiagonal >= 0 and lDiagonal < N:
      oldBoard[i,lDiagonal] += 1
  return oldBoard

def finishCheck(Queens, board):
  for i in Queens:
    if board[i][Queens[i]] != 0:
      return False
  return True

N = 8

#Make gameboard
board = np.zeros((N,N))

queensPos = {}

queensPos, board = placeQueens(queensPos, board, N)

while  not finishCheck(queensPos, board):
  for i in range(N):
    queensPos[i], board = moveQueens(queensPos[i], board, i, N)
    if finishCheck(queensPos, board):
      break

print(queensPos)
print(board)


{0: 2, 1: 7, 2: 3, 3: 6, 4: 0, 5: 5, 6: 1, 7: 4}
[[2. 2. 0. 2. 2. 2. 2. 2.]
 [1. 3. 2. 3. 3. 1. 2. 0.]
 [2. 1. 3. 0. 2. 3. 2. 2.]
 [2. 2. 2. 2. 3. 3. 0. 2.]
 [0. 3. 1. 2. 3. 3. 3. 3.]
 [3. 2. 3. 2. 2. 0. 3. 2.]
 [1. 0. 3. 3. 2. 2. 2. 2.]
 [2. 2. 3. 3. 0. 1. 1. 2.]]
